# Generated by Django 6.1.1 on 2026-09-28 18:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Fitness', max_length=100)),
                ('duration_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('habit_type', models.CharField(choices=[('boolean', 'Cumplimiento Sí/No'), ('numeric', 'Cuantitativo / Numérico')], default='boolean', max_length=20)),
                ('target_value', models.FloatField(default=1.0)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('frequency_type', models.CharField(choices=[('daily', 'Todos los días'), ('specific_days', 'Días específicos'), ('weekly_quota', 'Cuota semanal')], default='daily', max_length=20)),
                ('days_of_week', models.CharField(default='0,1,2,3,4,5,6', help_text='0=Lunes, 6=Domingo', max_length=50)),
                ('weekly_target', models.IntegerField(default=7)),
                ('sla_target_percent', models.IntegerField(default=80, help_text='Meta de cumplimiento porcentual para estar en SLA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='core.programenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day_offset', models.IntegerField(default=0, help_text='Día relativo del programa (0 es día 1, etc.)')),
                ('habit_type', models.CharField(choices=[('boolean', 'Cumplimiento Sí/No'), ('numeric', 'Cuantitativo / Numérico')], default='boolean', max_length=20)),
                ('target_value', models.FloatField(default=1.0)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('value', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
