# Generated by Django 6.1.1 on 2026-09-28 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tone', models.CharField(choices=[('drill_sergeant', 'Sargento Estricto (Sin Excusas / Militar)'), ('stoic_mentor', 'Mentor Estoico (Filosófico / Firme y Sabio)'), ('high_performance', 'Entrenador Élite (Enfoque Resultados / Atleta)'), ('empathetic_coach', 'Coach Comprensivo (Positivo / Hábito Sostenible)')], default='drill_sergeant', max_length=50)),
                ('avatar_emoji', models.CharField(default='🔥', max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('morning_quote', models.CharField(default='¡Despierta! Hoy es el día para mover la aguja.', max_length=255)),
                ('midday_reminder', models.CharField(default='¿Ya avanzaste en tu acción prioritaria?', max_length=255)),
                ('evening_warning', models.CharField(default='El día casi termina. No te vayas a dormir debiendo tu hábito.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoachPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('push_subscription', models.JSONField(blank=True, default=dict)),
                ('intensity_level', models.IntegerField(default=3, help_text='1: Suave, 2: Medio, 3: Implacable')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.coachprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
