# Generated by Django 6.1.1 on 2026-09-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coachprofile_usercoachpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='day_offset',
            field=models.IntegerField(blank=True, help_text='Día relativo del programa (0 es día 1, etc.)', null=True),
        ),
    ]
