# Generated by Django 6.1.1 on 2026-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_habit_day_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='estimated_minutes',
            field=models.IntegerField(default=5, help_text='Tiempo estimado en minutos para completar la tarea'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='estimated_minutes',
            field=models.IntegerField(default=5, help_text='Tiempo estimado en minutos para completar la tarea'),
        ),
    ]
