# Generated by Django 6.1.1 on 2026-10-06 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_habit_estimated_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Usuarios con quienes se comparte este hábito/lista', related_name='shared_habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
